'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace srvUno
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service.informatica.udistrital.edu.co", ConfigurationName:="srvUno.MeteorologiaWS")>  _
    Public Interface MeteorologiaWS
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function cargarValorSensorXIdSensor(ByVal idSensor As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="cargarValorSensorXIdSensorReturn")> srvUno.DatosMeteorologicosDTO
        
        'CODEGEN: Parameter 'cargarValorHistoricoXIdSensorReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function cargarValorHistoricoXIdSensor(ByVal request As srvUno.cargarValorHistoricoXIdSensorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="cargarValorHistoricoXIdSensorReturn")> srvUno.cargarValorHistoricoXIdSensorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub insertarDatos(ByVal estacion As Integer, ByVal latitud As String, ByVal longitud As String, ByVal dato As String, ByVal tipoDato As String, ByVal fecha As String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.informatica.udistrital.edu.co")>  _
    Partial Public Class DatosMeteorologicosDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private datoField As String
        
        Private estacionField As Integer
        
        Private fechaField As String
        
        Private latitudField As String
        
        Private longitudField As String
        
        Private tipoDatoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property dato() As String
            Get
                Return Me.datoField
            End Get
            Set
                Me.datoField = value
                Me.RaisePropertyChanged("dato")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property estacion() As Integer
            Get
                Return Me.estacionField
            End Get
            Set
                Me.estacionField = value
                Me.RaisePropertyChanged("estacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property latitud() As String
            Get
                Return Me.latitudField
            End Get
            Set
                Me.latitudField = value
                Me.RaisePropertyChanged("latitud")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property longitud() As String
            Get
                Return Me.longitudField
            End Get
            Set
                Me.longitudField = value
                Me.RaisePropertyChanged("longitud")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property tipoDato() As String
            Get
                Return Me.tipoDatoField
            End Get
            Set
                Me.tipoDatoField = value
                Me.RaisePropertyChanged("tipoDato")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cargarValorHistoricoXIdSensor", WrapperNamespace:="http://service.informatica.udistrital.edu.co", IsWrapped:=true)>  _
    Partial Public Class cargarValorHistoricoXIdSensorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.informatica.udistrital.edu.co", Order:=0)>  _
        Public idSensor As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idSensor As Integer)
            MyBase.New
            Me.idSensor = idSensor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cargarValorHistoricoXIdSensorResponse", WrapperNamespace:="http://service.informatica.udistrital.edu.co", IsWrapped:=true)>  _
    Partial Public Class cargarValorHistoricoXIdSensorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.informatica.udistrital.edu.co", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("cargarValorHistoricoXIdSensorReturn")>  _
        Public cargarValorHistoricoXIdSensorReturn() As srvUno.DatosMeteorologicosDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cargarValorHistoricoXIdSensorReturn() As srvUno.DatosMeteorologicosDTO)
            MyBase.New
            Me.cargarValorHistoricoXIdSensorReturn = cargarValorHistoricoXIdSensorReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MeteorologiaWSChannel
        Inherits srvUno.MeteorologiaWS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MeteorologiaWSClient
        Inherits System.ServiceModel.ClientBase(Of srvUno.MeteorologiaWS)
        Implements srvUno.MeteorologiaWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function cargarValorSensorXIdSensor(ByVal idSensor As Integer) As srvUno.DatosMeteorologicosDTO Implements srvUno.MeteorologiaWS.cargarValorSensorXIdSensor
            Return MyBase.Channel.cargarValorSensorXIdSensor(idSensor)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srvUno_MeteorologiaWS_cargarValorHistoricoXIdSensor(ByVal request As srvUno.cargarValorHistoricoXIdSensorRequest) As srvUno.cargarValorHistoricoXIdSensorResponse Implements srvUno.MeteorologiaWS.cargarValorHistoricoXIdSensor
            Return MyBase.Channel.cargarValorHistoricoXIdSensor(request)
        End Function
        
        Public Function cargarValorHistoricoXIdSensor(ByVal idSensor As Integer) As srvUno.DatosMeteorologicosDTO()
            Dim inValue As srvUno.cargarValorHistoricoXIdSensorRequest = New srvUno.cargarValorHistoricoXIdSensorRequest()
            inValue.idSensor = idSensor
            Dim retVal As srvUno.cargarValorHistoricoXIdSensorResponse = CType(Me,srvUno.MeteorologiaWS).cargarValorHistoricoXIdSensor(inValue)
            Return retVal.cargarValorHistoricoXIdSensorReturn
        End Function
        
        Public Sub insertarDatos(ByVal estacion As Integer, ByVal latitud As String, ByVal longitud As String, ByVal dato As String, ByVal tipoDato As String, ByVal fecha As String) Implements srvUno.MeteorologiaWS.insertarDatos
            MyBase.Channel.insertarDatos(estacion, latitud, longitud, dato, tipoDato, fecha)
        End Sub
    End Class
End Namespace
